/* Aseuro site behaviour: navigation, catalogue, cart and WhatsApp checkout. */
const WHATSAPP_NUMBER = '919999999999'; // Replace with your full WhatsApp number, country code first, no + or spaces.
const money = value => new Intl.NumberFormat('en-IN', {style: 'currency', currency: 'INR', maximumFractionDigits: 0}).format(value);
const getCart = () => JSON.parse(localStorage.getItem('aseuro-cart') || '[]');
const saveCart = cart => { localStorage.setItem('aseuro-cart', JSON.stringify(cart)); updateCartCount(); };
const getProduct = id => products.find(product => product.id === Number(id));

function updateCartCount() { const count = getCart().reduce((sum, item) => sum + item.quantity, 0); document.querySelectorAll('.cart-count').forEach(el => el.textContent = count); }
function addToCart(id, quantity = 1) { const cart = getCart(); const existing = cart.find(item => item.id === id); if (existing) existing.quantity += quantity; else cart.push({id, quantity}); saveCart(cart); }
function productCard(product) { return `<article class="product-card"><a href="product.html?id=${product.id}" class="product-image">${product.badge ? `<span class="badge">${product.badge}</span>` : ''}<img src="${product.image}" alt="${product.name}"></a><div class="product-info"><p>${product.category}</p><h3><a href="product.html?id=${product.id}">${product.name}</a></h3><div class="product-bottom"><b>${money(product.price)}</b><button class="add-icon" data-add="${product.id}" aria-label="Add ${product.name} to cart">+</button></div></div></article>`; }
function renderHeader() { const header = document.getElementById('site-header'); if (!header) return; header.innerHTML = `<header class="site-header"><a class="brand" href="index.html">aseuro<span>.</span></a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false">☰</button><nav class="nav"><a href="index.html">Home</a><a href="shop.html">Shop</a><a href="about.html">About us</a><a href="contact.html">Contact us</a></nav><a class="cart-link" href="cart.html" aria-label="Shopping cart">Bag <span class="cart-count">0</span></a></header>`; header.querySelector('.menu-toggle').addEventListener('click', e => { header.querySelector('.nav').classList.toggle('open'); e.currentTarget.setAttribute('aria-expanded', header.querySelector('.nav').classList.contains('open')); }); }
function renderFooter() { const footer = document.getElementById('site-footer'); if (footer) footer.innerHTML = `<footer><div><a class="brand" href="index.html">aseuro<span>.</span></a><p>Thoughtful essentials for everyday care.</p></div><div><b>Explore</b><a href="shop.html">Shop</a><a href="about.html">About us</a><a href="contact.html">Contact us</a></div><div><b>Need help?</b><a id="footer-whatsapp" href="#">WhatsApp us</a><a href="cart.html">Your bag</a></div><small>© ${new Date().getFullYear()} Aseuro. All rights reserved.</small></footer>`; }
function setupWhatsApp() { const link = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent('Hello Aseuro! I would like some help.')}`; ['whatsapp-float','contact-whatsapp','footer-whatsapp'].forEach(id => { const el = document.getElementById(id); if (el) el.href = link; }); }
function renderFeatured() { const node = document.getElementById('featured-products'); if (node) node.innerHTML = products.slice(0, 4).map(productCard).join(''); }
function renderShop(category = 'All') { const node = document.getElementById('shop-products'); if (node) node.innerHTML = products.filter(p => category === 'All' || p.category === category).map(productCard).join('') || '<p>No products in this category yet.</p>'; }
function renderDetail() { const node = document.getElementById('product-detail'); if (!node) return; const product = getProduct(new URLSearchParams(location.search).get('id')) || products[0]; document.title = `${product.name} | Aseuro`; node.innerHTML = `<section class="product-detail"><div class="detail-image"><img src="${product.image}" alt="${product.name}"></div><div class="detail-copy"><p class="eyebrow">${product.category}</p><h1>${product.name}</h1><p class="price">${money(product.price)}</p><p>${product.description}</p><ul>${product.details.map(detail => `<li>${detail}</li>`).join('')}</ul><div class="quantity-picker"><button data-qty="-1" aria-label="Reduce quantity">−</button><span id="product-quantity">1</span><button data-qty="1" aria-label="Increase quantity">+</button></div><button class="btn btn-dark full" id="add-detail" data-id="${product.id}">Add to bag — ${money(product.price)}</button><p class="microcopy">Questions before ordering? <a id="detail-whatsapp" href="#">Message us on WhatsApp.</a></p></div></section>`; let quantity = 1; node.querySelectorAll('[data-qty]').forEach(button => button.addEventListener('click', () => { quantity = Math.max(1, quantity + Number(button.dataset.qty)); node.querySelector('#product-quantity').textContent = quantity; })); node.querySelector('#add-detail').addEventListener('click', () => { addToCart(product.id, quantity); node.querySelector('#add-detail').textContent = 'Added to bag ✓'; setTimeout(() => node.querySelector('#add-detail').textContent = `Add to bag — ${money(product.price)}`, 1200); }); const wa = node.querySelector('#detail-whatsapp'); wa.href = `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(`Hello Aseuro! I have a question about ${product.name}.`)}`; }
function renderCart() { const node = document.getElementById('cart-items'); if (!node) return; const cart = getCart(); const total = cart.reduce((sum, item) => sum + getProduct(item.id).price * item.quantity, 0); document.getElementById('cart-total').textContent = money(total); if (!cart.length) { node.innerHTML = `<div class="empty-cart"><h2>Your bag is waiting.</h2><p>Add a little everyday care to get started.</p><a class="btn btn-dark" href="shop.html">Explore products</a></div>`; return; } node.innerHTML = cart.map(item => { const p = getProduct(item.id); return `<article class="cart-item"><img src="${p.image}" alt="${p.name}"><div><p class="eyebrow">${p.category}</p><h3>${p.name}</h3><b>${money(p.price)}</b><div class="cart-actions"><div class="quantity-picker"><button data-change="-1" data-id="${p.id}" aria-label="Reduce ${p.name} quantity">−</button><span>${item.quantity}</span><button data-change="1" data-id="${p.id}" aria-label="Increase ${p.name} quantity">+</button></div><button class="remove" data-remove="${p.id}">Remove</button></div></div><b>${money(p.price * item.quantity)}</b></article>`; }).join(''); node.querySelectorAll('[data-change]').forEach(button => button.addEventListener('click', () => changeQuantity(Number(button.dataset.id), Number(button.dataset.change)))); node.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => removeFromCart(Number(button.dataset.remove)))); }
function changeQuantity(id, change) { let cart = getCart(); const item = cart.find(i => i.id === id); item.quantity += change; if (item.quantity < 1) cart = cart.filter(i => i.id !== id); saveCart(cart); renderCart(); }
function removeFromCart(id) { saveCart(getCart().filter(item => item.id !== id)); renderCart(); }
function setupCheckout() { const form = document.getElementById('checkout-form'); if (!form) return; form.addEventListener('submit', event => { event.preventDefault(); const cart = getCart(); if (!cart.length) return alert('Your bag is empty. Please add a product first.'); const data = Object.fromEntries(new FormData(form)); const lines = cart.map(item => { const p = getProduct(item.id); return `• ${p.name} × ${item.quantity} — ${money(p.price * item.quantity)}`; }); const total = cart.reduce((sum, item) => sum + getProduct(item.id).price * item.quantity, 0); const message = `Hello Aseuro! I would like to place an order.%0A%0AName: ${data.name}%0APhone: ${data.phone}%0AAddress: ${data.address}%0A%0AOrder:%0A${lines.join('%0A')}%0A%0ATotal: ${money(total)}`; window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${message}`, '_blank'); }); }

document.addEventListener('DOMContentLoaded', () => { renderHeader(); renderFooter(); updateCartCount(); setupWhatsApp(); renderFeatured(); renderShop(); renderDetail(); renderCart(); setupCheckout(); document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.filter').forEach(b => b.classList.remove('active')); button.classList.add('active'); renderShop(button.dataset.category); })); document.addEventListener('click', event => { const button = event.target.closest('[data-add]'); if (button) { addToCart(Number(button.dataset.add)); button.textContent = '✓'; setTimeout(() => button.textContent = '+', 900); } }); });
