/* Edit this list to update your catalogue. Image files live in /images. */
const products = [
  {id: 1, name: 'Velvet Glow Face Serum', category: 'Skincare', price: 1899, image: 'images/velvet-glow-face-serum.jpg', badge: 'Bestseller', description: 'A lightweight daily serum made to leave skin looking rested, smooth and beautifully hydrated.', details: ['30 ml glass bottle', 'Suitable for daily use', 'Lightweight, non-greasy finish']},
  {id: 2, name: 'Daily Dew Cleanser', category: 'Skincare', price: 1499, image: 'images/product-cleanser.svg', badge: 'New', description: 'A gentle, refreshing cleanser for the first quiet moment of your routine.', details: ['150 ml pump bottle', 'Gentle daily cleanse', 'Fresh, soft finish']},
  {id: 3, name: 'Silk Touch Lip Balm', category: 'Beauty', price: 1299, image: 'images/product-lipbalm.svg', badge: '', description: 'A comforting lip balm with a silky feel and a subtle everyday sheen.', details: ['10 g compact tin', 'Comforting texture', 'Easy to carry']},
  {id: 4, name: 'Bloom Body Lotion', category: 'Beauty', price: 1799, image: 'images/product-lotion.svg', badge: 'Popular', description: 'A soft, nourishing body lotion designed for your everyday reset.', details: ['250 ml bottle', 'Quick-absorbing lotion', 'Warm, clean fragrance']},
  {id: 5, name: 'Fresh Mint Toothpaste', category: 'Oral Care', price: 999, image: 'images/product-toothpaste.svg', badge: '', description: 'An everyday toothpaste that leaves your smile feeling clean and fresh.', details: ['100 g tube', 'Fresh mint flavour', 'Everyday oral care']},
  {id: 6, name: 'Soft Bristle Toothbrush', category: 'Oral Care', price: 799, image: 'images/product-toothbrush.svg', badge: '', description: 'A comfortable soft-bristle toothbrush made for a gentle daily clean.', details: ['Pack of 2', 'Soft bristles', 'Easy-grip handle']},
  {id: 7, name: 'Gentle Pet Shampoo', category: 'Pet Care', price: 1699, image: 'images/product-pet-shampoo.svg', badge: 'Pet favourite', description: 'A gentle wash for a soft, clean coat and more cuddle-ready moments.', details: ['250 ml bottle', 'Gentle cleansing', 'For dogs and cats']},
  {id: 8, name: 'Cozy Pet Treats', category: 'Pet Care', price: 1199, image: 'images/product-treats.svg', badge: '', description: 'Little treats for the pet who makes every day better.', details: ['100 g pouch', 'Bite-sized treats', 'For rewarding good moments']}
];
